"""What every emitter needs and none of them should restate.

Six emitters that each decided for themselves what image to use, how to name a
container, or which port the API listens on would drift within a release — and
the drift would be invisible, because each file is read on its own.
"""

from __future__ import annotations

from typing import Iterable

from ..manifest import Component, Deployment

#: The published image. One string, so a version bump is one edit rather than
#: six that somebody has to find.
IMAGE = "ghcr.io/slpie/slpie"
TAG = "latest"

#: Where each component listens. Stated once and read by every emitter, the
#: install manual included — which is what makes the manual's ports the same
#: ports the deployment opens rather than the same ports somebody remembered.
PORTS = {"api": 8765, "ui": 8765, "scheduler": 0, "workers": 0}

#: The command each component runs. A component nobody named here gets the
#: worker command, because that is what an unnamed pool is.
COMMANDS = {
    "api": ("slpie", "serve", "--host", "0.0.0.0", "--port", "8765"),
    "ui": ("slpie", "ui", "--host", "0.0.0.0", "--port", "8765"),
    "scheduler": ("slpie", "schedule"),
    "workers": ("slpie", "work"),
}

#: Kubernetes' own units are not Docker's. `4Gi` is a Kubernetes quantity and
#: compose wants `4g`, and translating in one place is what stops five emitters
#: each inventing a slightly different rule.
_SUFFIXES = {"Gi": "g", "Mi": "m", "Ki": "k", "G": "g", "M": "m", "K": "k"}


def image() -> str:
    return f"{IMAGE}:{TAG}"


def command_for(component: Component) -> tuple[str, ...]:
    base = COMMANDS.get(component.name, COMMANDS["workers"])
    if component.queues:
        return base + ("--queues", ",".join(component.queues))
    return base


def port_for(component: Component) -> int:
    return PORTS.get(component.name, 0)


def docker_memory(quantity: str) -> str:
    """`4Gi` → `4g`. An unrecognised quantity is passed through untouched.

    Passed through rather than rejected: an operator who wrote something this
    table does not know still gets it in the file, where Docker will complain
    about it in terms they can act on. Silently dropping it would produce a
    container with no memory limit and no explanation.
    """
    for suffix, replacement in _SUFFIXES.items():
        if quantity.endswith(suffix):
            return quantity[: -len(suffix)] + replacement
    return quantity


def environment_for(deployment: Deployment) -> dict[str, str]:
    """The variables every component needs, from the manifest and nowhere else."""
    values = {"SLPIE_ENVIRONMENT": deployment.environment}

    graph = deployment.persistence.get("graph")
    if graph and graph.engine == "postgres":
        # The value is a placeholder on purpose. A rendered artifact that
        # carried a real connection string would be a credential in a file
        # somebody is about to commit.
        values["SLPIE_DATABASE_URL"] = "${SLPIE_DATABASE_URL}"

    broker = deployment.persistence.get("broker")
    if broker:
        values["SLPIE_BROKER_URL"] = "${SLPIE_BROKER_URL}"

    objects = deployment.persistence.get("objects")
    if objects and objects.bucket:
        values["SLPIE_OBJECT_BUCKET"] = objects.bucket

    if deployment.regions.primary:
        values["SLPIE_REGION"] = deployment.regions.primary
    return dict(sorted(values.items()))


def header(deployment: Deployment, *, comment: str = "#") -> list[str]:  # noqa: D401
    """The banner every rendered file carries.

    It names the source, because the first question anybody asks of a generated
    file is where it came from — and the second is whether editing it is
    pointless, which the third line answers.
    """
    mark = f"{comment} " if comment else ""
    lines = [
        f"{mark}Generated by `slpie deploy render` from the deployment manifest.",
        f"{mark}Environment: {deployment.environment} · platform: "
        f"{deployment.platform.value} · cloud: {deployment.cloud.value}",
        f"{mark}Edits here are lost on the next render. Change the manifest.",
    ]
    if deployment.source_uri:
        lines.insert(1, f"{mark}Source: {deployment.source_uri}")
    return lines


def indent(lines: Iterable[str], by: int) -> list[str]:
    pad = " " * by
    return [f"{pad}{line}" if line else "" for line in lines]
