"""Rendering ledger revisions as Alembic migration scripts.

The ledger is the source of truth; Alembic is one of the places that truth has
to land. This adapter renders revisions into Alembic's script format, which
works whether or not Alembic is installed — the output is text, and text does
not need the library that will later read it.

Type mapping is conservative. A shape says ``int``; whether that is a
``BigInteger`` or a ``SmallInteger`` in a given warehouse is a decision the
adapter does not have the evidence to make, so it picks the widest safe option
and says so in the generated comment.
"""

from __future__ import annotations

import importlib.util
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

from ..errors import MigrationError
from ..ids import iso, slug
from ..meta import TypeTag
from .ledger import LOSSY, MigrationLedger, Operation, OpKind, Revision

#: Portable shape types to SQLAlchemy column types.
SA_TYPES: dict[str, str] = {
    TypeTag.BOOL.value: "sa.Boolean()",
    TypeTag.INT.value: "sa.BigInteger()",
    TypeTag.FLOAT.value: "sa.Float()",
    TypeTag.DECIMAL.value: "sa.Numeric(38, 9)",
    TypeTag.STRING.value: "sa.Text()",
    TypeTag.BYTES.value: "sa.LargeBinary()",
    TypeTag.MEDIA.value: "sa.LargeBinary()",
    TypeTag.DATE.value: "sa.Date()",
    TypeTag.DATETIME.value: "sa.DateTime(timezone=True)",
    TypeTag.DURATION.value: "sa.Interval()",
    TypeTag.UUID.value: "sa.String(36)",
    TypeTag.LIST.value: "sa.JSON()",
    TypeTag.STRUCT.value: "sa.JSON()",
    TypeTag.MAP.value: "sa.JSON()",
    TypeTag.JSON.value: "sa.JSON()",
    TypeTag.NULL.value: "sa.Text()",
}

_SCRIPT = '''"""{message}

Generated by Gratimos from ledger revision {revision}.
Entity: {entity}
Reversible: {reversible}{lossy_note}

Revision ID: {revision}
Revises: {down_revision}
Create Date: {created}
"""

from alembic import op
import sqlalchemy as sa

revision = {revision!r}
down_revision = {down_revision!r}
branch_labels = None
depends_on = None


def upgrade() -> None:
{upgrade}


def downgrade() -> None:
{downgrade}
'''


def alembic_available() -> bool:
    try:
        return importlib.util.find_spec("alembic") is not None
    except (ImportError, ValueError):  # pragma: no cover
        return False


def sa_type(name: str) -> str:
    return SA_TYPES.get(name, "sa.Text()")


@dataclass(frozen=True, slots=True)
class RenderedMigration:
    """One Alembic script, ready to write."""

    revision: str
    entity: str
    filename: str
    source: str
    reversible: bool

    def write(self, directory: str | Path) -> Path:
        target = Path(directory).expanduser()
        target.mkdir(parents=True, exist_ok=True)
        path = target / self.filename
        path.write_text(self.source, encoding="utf-8")
        return path

    def to_dict(self) -> dict[str, Any]:
        return {
            "revision": self.revision, "entity": self.entity,
            "filename": self.filename, "reversible": self.reversible,
            "lines": self.source.count("\n") + 1,
        }


class AlembicAdapter:
    """Renders ledger revisions into Alembic scripts."""

    def __init__(self, *, table_prefix: str = "", schema: str = "") -> None:
        self.table_prefix = table_prefix
        self.schema = schema

    def table_of(self, entity: str) -> str:
        return f"{self.table_prefix}{slug(entity)}"

    def render(self, revision: Revision) -> RenderedMigration:
        """Turn one revision into a migration script."""
        upgrade = self._body(revision.operations)
        downgrade_ops = revision.downgrade_ops()
        if downgrade_ops:
            downgrade = self._body(downgrade_ops)
        else:
            lost = ", ".join(
                op.describe() for op in revision.operations if op.kind in LOSSY
            )
            downgrade = (
                "    # This revision is not reversible: "
                f"{lost}.\n"
                "    # The structure could be recreated, but the data it held cannot be.\n"
                "    raise NotImplementedError(\n"
                f"        {('cannot downgrade ' + revision.revision + ': ' + lost)!r}\n"
                "    )"
            )

        source = _SCRIPT.format(
            message=revision.message or f"update {revision.entity}",
            revision=revision.revision,
            down_revision=revision.down_revision or None,
            entity=revision.entity,
            reversible=revision.reversible,
            lossy_note="\nWARNING: discards data that cannot be recovered by downgrade."
            if revision.lossy else "",
            created=iso(revision.ts_ns),
            upgrade=upgrade,
            downgrade=downgrade,
        )
        return RenderedMigration(
            revision=revision.revision,
            entity=revision.entity,
            filename=f"{revision.revision}_{slug(revision.entity)}.py",
            source=source,
            reversible=revision.reversible,
        )

    def render_all(self, ledger: MigrationLedger, *, entity: str = "",
                   pending_only: bool = True) -> list[RenderedMigration]:
        revisions = ledger.pending(entity) if pending_only else ledger.revisions(entity)
        return [self.render(r) for r in revisions]

    def write_all(self, ledger: MigrationLedger, directory: str | Path, **kwargs: Any) -> list[Path]:
        return [m.write(directory) for m in self.render_all(ledger, **kwargs)]

    # -- operation rendering ---------------------------------------------

    def _body(self, operations: Sequence[Operation]) -> str:
        lines = [self._line(op) for op in operations]
        return "\n".join(lines) if lines else "    pass"

    def _line(self, op: Operation) -> str:
        table = self.table_of(op.entity)
        schema = f", schema={self.schema!r}" if self.schema else ""
        column = slug(op.field_name) if op.field_name else ""

        if op.kind is OpKind.CREATE_ENTITY:
            return (
                f"    op.create_table(\n"
                f"        {table!r},\n"
                f"        sa.Column('id', sa.BigInteger(), primary_key=True, autoincrement=True),\n"
                f"    {schema.lstrip(', ') and schema.lstrip(', ') + ',' or ''}\n"
                f"    )"
            ).replace("\n    \n", "\n")
        if op.kind is OpKind.DROP_ENTITY:
            return f"    op.drop_table({table!r}{schema})"
        if op.kind is OpKind.ADD_FIELD:
            nullable = "True" if op.nullable is None else str(bool(op.nullable))
            return (
                f"    op.add_column(\n"
                f"        {table!r},\n"
                f"        sa.Column({column!r}, {sa_type(op.to_type)}, nullable={nullable}),\n"
                f"    {schema.lstrip(', ') and schema.lstrip(', ') + ',' or ''}\n"
                f"    )"
            ).replace("\n    \n", "\n")
        if op.kind is OpKind.DROP_FIELD:
            return f"    op.drop_column({table!r}, {column!r}{schema})"
        if op.kind is OpKind.ALTER_TYPE:
            return (
                f"    op.alter_column(\n"
                f"        {table!r}, {column!r},\n"
                f"        existing_type={sa_type(op.from_type)},\n"
                f"        type_={sa_type(op.to_type)},\n"
                f"        postgresql_using={f'{column}::{_pg_cast(op.to_type)}'!r},\n"
                f"    )"
            )
        if op.kind is OpKind.ALTER_NULLABLE:
            return (
                f"    op.alter_column(\n"
                f"        {table!r}, {column!r},\n"
                f"        nullable={bool(op.nullable)},\n"
                f"    )"
            )
        if op.kind is OpKind.RENAME_FIELD:
            new_name = slug(str(op.detail.get("to", "")))
            return f"    op.alter_column({table!r}, {column!r}, new_column_name={new_name!r}{schema})"
        return f"    pass  # unhandled operation: {op.kind.value}"


def _pg_cast(type_name: str) -> str:
    """The Postgres cast used when a widening alter needs an explicit USING."""
    return {
        TypeTag.INT.value: "bigint",
        TypeTag.FLOAT.value: "double precision",
        TypeTag.DECIMAL.value: "numeric",
        TypeTag.BOOL.value: "boolean",
        TypeTag.DATE.value: "date",
        TypeTag.DATETIME.value: "timestamptz",
    }.get(type_name, "text")


def require_alembic() -> Any:
    """Import Alembic or explain how to get it."""
    if not alembic_available():
        raise MigrationError(
            "alembic is not installed; install it with: pip install 'gratimos[sql]'. "
            "Rendering migration scripts does not require it — only running them does."
        )
    import alembic  # noqa: PLC0415

    return alembic
