"""C4 as Mermaid — a specialised renderer, not a duplicate of the generic one.

Lifted out of `C4View` unchanged, and kept separate from `present.mermaid`
because its output is C4-shaped rather than merely diagram-shaped: external
systems go in their own subgraph, and an element's outline follows its kind. A
renderer that flattened those would produce something that looks like a C4
diagram and is not one, which is worse than producing nothing.

It lives here for the same reason everything else in this package does: the
model states its shape, and drawing is downstream of that. `slpie/artifacts/c4.py`
now builds views and does not know Mermaid exists.
"""

from __future__ import annotations

from typing import Any

from ..domain.node import NodeKind

#: Outline per kind, so a reader can tell a datastore from a service without
#: reading the label. Mermaid's own shape syntax, which is why it is here.
SHAPES = {
    NodeKind.DATABASE: ("[(", ")]"),
    NodeKind.SERVICE: ("([", "])"),
    NodeKind.PACKAGE: ("[", "]"),
    NodeKind.DEPLOYMENT: ("[[", "]]"),
}
DEFAULT_SHAPE = ("[", "]")


def mermaid(view: Any) -> str:
    """One C4 view as a Mermaid flowchart. Stable line order by construction."""
    lines = [
        f"%% C4 level {view.level.number} — {view.level.title}"
        + (f" — {view.scope}" if view.scope else ""),
        "%% generated by SLPIE from the knowledge graph; do not edit by hand",
        "flowchart TD",
    ]
    internal = [element for element in view.elements if not element.external]
    external = [element for element in view.elements if element.external]

    for element in internal:
        lines.append("    " + element_line(element))
    if external:
        lines.append('    subgraph external["External"]')
        for element in external:
            lines.append("        " + element_line(element))
        lines.append("    end")

    # No endpoint check here. The builder only ever emits relationships whose
    # *both* ends are in the same selection these elements came from, so a guard
    # would be a branch no input can reach — and an unreachable guard is worse
    # than none: it reads as though the invariant were in doubt, and it hides
    # the one place the invariant is actually enforced.
    for relationship in view.relationships:
        lines.append(
            f'    {relationship.source} -->|"{escape(relationship.label)}"| '
            f"{relationship.target}"
        )
    return "\n".join(lines) + "\n"


def element_line(element: Any) -> str:
    known = element.kind in NodeKind._value2member_map_
    open_shape, close_shape = (
        SHAPES.get(NodeKind(element.kind), DEFAULT_SHAPE) if known else DEFAULT_SHAPE
    )
    detail = element.technology or element.kind
    return (
        f'{element.alias}{open_shape}"{escape(element.label)}'
        f'<br/><small>[{escape(detail)}]</small>"{close_shape}'
    )


def escape(text: str) -> str:
    """Mermaid label text: quotes and brackets would end the label early."""
    return (
        str(text)
        .replace("\\", "/")
        .replace('"', "'")
        .replace("[", "(")
        .replace("]", ")")
        .replace("\n", " ")
    )
