"""The index, rendered for whoever picks this product up next.

Two halves, and the split is the whole design.

**`SKILL.md` is hand-written and stable.** The invariants, the ring rule, the
operating policy, the doctrine that has actually been paid for. Those change
rarely and deliberately, and a generator would have nothing to derive them from.

**`INDEX.md` and `index.json` are generated from `ContextIndex`.** The verb→
route→screen→test chains, the section claims, the component vocabulary, the
coverage white space. Those change every commit, and a hand-written map of 340
modules is wrong within two releases — which is precisely the argument §18 makes
for generating `docs/INSTALL.md` and §25 makes for auditing the reference
registry rather than trusting it.

Committed rather than produced on demand, and gated by `--check`, for the reason
the four contract emitters are: regenerating once is not a fix. The permanent
fix is a test that fails when the committed artifact and its generator disagree,
which is the same `--check` discipline `tools/notebooks/build.py` already uses.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Iterable

from .facet import Facet, FacetKind, Relation
from .index import ContextIndex

#: Where the generated half lives. A Claude Code skill directory, so the map is
#: loaded by the tool that needs it rather than pasted into a prompt.
SKILL_DIR = Path(".claude") / "skills" / "slpie"

GENERATED = ("INDEX.md", "index.json")

#: An open finding in `docs/AUDIT.md`: a numbered heading under a part.
AUDIT_ITEM = re.compile(r"^### (\d+\.\d+) (.+)$", re.M)

HEADER = """<!-- Generated by `slpie context --skill`. Do not edit.
     The hand-written half of this skill is SKILL.md, which is not generated. -->

# The map

Every line below is read from the code, not maintained beside it: verbs from
`slpie/compose/registry.py`, routes from `Api.routes`, screens from
`slpie/ui/contract.py`, modules and imports from `slpie/audit/project.py`, plan
sections from the `§NN` references modules write in their own docstrings.

If this file disagrees with the codebase, the codebase is right and this file is
stale — regenerate it with `slpie context --skill`. It cannot disagree for long:
`tests/test_slpie_context.py` fails when it does.
"""


def _table(rows: Iterable[tuple[str, ...]], headers: tuple[str, ...]) -> list[str]:
    """A markdown table. Rows are already strings; nothing here formats data."""
    rows = list(rows)
    if not rows:
        return ["_Nothing._", ""]
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(["---"] * len(headers)) + "|",
    ]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    lines.append("")
    return lines


def _capability_rows(index: ContextIndex) -> list[tuple[str, ...]]:
    """One row per verb: the whole chain from capability to test.

    This is the table that answers the question a cold session actually asks —
    *where does `findings` live, what serves it, what screen shows it, and what
    proves it works* — in one line instead of four greps.
    """
    rows: list[tuple[str, ...]] = []
    for verb in index.of_kind(FacetKind.VERB):
        screens = [
            facet.name for facet in index.into(verb.id, Relation.RUNS)
            if facet.kind is FacetKind.SCREEN
        ]
        produces = [
            target.split(":", 1)[1] for target in verb.linked(Relation.PRODUCES)
        ]
        consumes = [
            target.split(":", 1)[1] for target in verb.linked(Relation.CONSUMES)
        ]
        rows.append((
            f"`{verb.name}`",
            verb.tags[0] if verb.tags else "",
            f"{(consumes or ['?'])[0]} → {(produces or ['?'])[0]}",
            f"`{verb.source}`" if verb.source else "**unanchored**",
            ", ".join(screens) or "inspector",
        ))
    return rows


def _untested(index: ContextIndex, ring: str = "slpie") -> list[tuple[str, ...]]:
    """Modules no test file reaches by name, directly or through their package.

    The package fallback is what keeps this honest. A `COVERS` link means *a
    test imports this module by name*, and plenty of modules are exercised
    entirely through their package's `__init__` — reporting those as untested
    would be a number that looks like a coverage crisis and is an artefact of
    how the tests import. What survives the fallback is the real white space.

    It is still an import-graph fact rather than a statement about execution:
    `pytest --cov` measures what ran. This measures what is *named*, which is a
    different and cheaper question, and the one a reader orienting themselves is
    actually asking — where would I even look for a test of this.
    """
    gaps: list[tuple[str, ...]] = []
    for facet in index.facets:
        if facet.kind not in (FacetKind.MODULE, FacetKind.PACKAGE):
            continue
        if not facet.name.startswith(f"{ring}."):
            continue
        if index.into(facet.id, Relation.COVERS):
            continue
        parent = facet.name.rsplit(".", 1)[0]
        if index.into(f"package:{parent}", Relation.COVERS):
            continue
        gaps.append((f"`{facet.name}`", facet.source))
    return gaps


def _section_rows(index: ContextIndex) -> list[tuple[str, ...]]:
    rows: list[tuple[str, ...]] = []
    for section in index.of_kind(FacetKind.SECTION):
        claimers = [
            facet for facet in index.into(section.id, Relation.CLAIMS)
        ]
        packages = sorted({
            facet.name.rsplit(".", 1)[0] if facet.kind is FacetKind.MODULE
            else facet.name
            for facet in claimers
        })
        rows.append((
            section.title,
            str(len(claimers)),
            ", ".join(f"`{name}`" for name in packages[:5]) or "—",
        ))
    return rows


def _screen_rows(index: ContextIndex) -> list[tuple[str, ...]]:
    rows: list[tuple[str, ...]] = []
    for screen in index.of_kind(FacetKind.SCREEN):
        if "view" in screen.tags:
            continue                      # a view renders as a tab on its parent
        views = sorted(
            facet.name for facet in index.into(screen.id, Relation.PARENT)
        )
        reads = sorted(
            target.split(":", 1)[1] for target in screen.linked(Relation.READS)
        )
        rows.append((
            f"`{screen.name}`",
            screen.tags[0] if screen.tags else "",
            "authored" if "authored" in screen.tags else "generated",
            ", ".join(views) or "—",
            f"{len(reads)}",
        ))
    return rows


def _audit_items(root: Path) -> list[tuple[str, ...]]:
    """The open findings recorded in `docs/AUDIT.md`, by their own numbering."""
    path = root / "docs" / "AUDIT.md"
    if not path.is_file():
        return []
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return []
    return [(number, title.strip()) for number, title in AUDIT_ITEM.findall(text)]


def render_markdown(index: ContextIndex) -> str:
    """`INDEX.md` — the map, for reading."""
    counts = index.to_dict()["counts"]
    lines: list[str] = [HEADER, ""]

    lines += [
        "## At a glance",
        "",
        f"- **digest** `{index.digest}`",
        f"- **facets** {len(index)} — "
        + ", ".join(f"{counts[key]} {key}" for key in sorted(counts)),
        f"- **anchored** {index.coverage:.1%} resolve to a file and a line",
        f"- **dangling** {len(index.dangling)} link(s) point at a facet that "
        "does not exist",
        "",
        "A dangling link is drift with an address attached — a screen reading a "
        "route nobody serves, or a test covering a module that was deleted. The "
        "number above is meant to be zero, and when it is not, "
        "`slpie context --json` names each one.",
        "",
        "## Capabilities, end to end",
        "",
        "Every verb, its type signature, where it is declared, and the screen "
        "that runs it. A verb whose screen column reads `inspector` has no "
        "designed home and is reached through the generated one — which is the "
        "rule that keeps every capability reachable from somewhere.",
        "",
    ]
    lines += _table(
        _capability_rows(index),
        ("verb", "group", "type", "declared at", "screens"),
    )

    untested = _untested(index)
    lines += [
        "## Where no test names the code",
        "",
        f"{len(untested)} module(s) under `slpie/` that no test file imports, "
        "directly or through their package. Not a coverage number — "
        "`pytest --cov` measures what *ran*, this measures what is *named* — "
        "but it is the cheap question a reader actually has: where would I look "
        "for a test of this.",
        "",
    ]
    lines += _table(untested, ("module", "source"))

    lines += [
        "## Plan sections, as the code claims them",
        "",
        "Derived from the `§NN` references modules write in their own "
        "docstrings — never from a map kept here. A section absent from this "
        "table is one no module claims to implement, which is a more useful "
        "signal than an invented owner.",
        "",
    ]
    lines += _table(_section_rows(index), ("section", "modules", "packages"))

    lines += [
        "## Screens",
        "",
        "Destinations only. A screen with a parent is a *view of* something and "
        "renders as a tab on its parent's page rather than a rail row — see "
        "`Screen.is_destination` in `slpie/ui/contract.py`.",
        "",
    ]
    lines += _table(
        _screen_rows(index),
        ("screen", "section", "kind", "views", "routes read"),
    )

    components = index.of_kind(FacetKind.COMPONENT)
    lines += [
        "## The browser vocabulary",
        "",
        f"{len(components)} component(s), read from the exports of the app's own "
        "modules. This is the dictionary a screen block indexes into: a block "
        "naming something absent from this list is a dangling link, caught in "
        "Python rather than found as a blank area in a browser.",
        "",
    ]
    by_module: dict[str, list[str]] = {}
    for facet in components:
        by_module.setdefault(facet.tags[0] if facet.tags else "?", []).append(facet.name)
    lines += _table(
        [(f"`ui/{module}.js`", ", ".join(f"`{name}`" for name in sorted(names)))
         for module, names in sorted(by_module.items())],
        ("module", "exports"),
    )

    unanchored = index.unanchored
    lines += [
        "## What could not be anchored",
        "",
        "Kept and counted, never dropped. An index that silently omitted what it "
        "could not place would describe a smaller, cleaner product than the one "
        "that exists — the same reason `Verdict.INDETERMINATE` exists in "
        "`slpie/audit/judge.py`.",
        "",
    ]
    lines += _table(
        [(f"`{facet.id}`", facet.kind.value) for facet in unanchored],
        ("facet", "kind"),
    )

    items = _audit_items(index.root)
    if items:
        lines += [
            "## Open findings",
            "",
            "From `docs/AUDIT.md`, by its own numbering. Read there for the "
            "command that reproduces each one.",
            "",
        ]
        lines += _table(items, ("#", "finding"))

    return "\n".join(lines).rstrip() + "\n"


def render_json(index: ContextIndex) -> str:
    """`index.json` — the map, for querying.

    Every facet, in full. A skill reading this can answer *what connects to X*
    without running Python, which is the point: the map has to be readable by
    whoever picks the product up, and that is not always a process that can
    import `slpie`.
    """
    body = {
        "generator": "slpie context --skill",
        "digest": index.digest,
        "summary": index.to_dict(),
        "facets": [facet.to_dict() for facet in index],
    }
    return json.dumps(body, indent=2, sort_keys=False) + "\n"


def artifacts(index: ContextIndex) -> dict[str, str]:
    """The generated files, by name. One place both `write` and the test read."""
    return {"INDEX.md": render_markdown(index), "index.json": render_json(index)}


def write(index: ContextIndex, *, check: bool = False) -> list[str]:
    """Write the generated half, or report what differs.

    Returns the lines to show the caller: empty when everything is in step. In
    `check` mode nothing is written and the return value names the files that
    would change, which is what makes this usable as a CI gate.
    """
    target = index.root / SKILL_DIR
    messages: list[str] = []
    produced = artifacts(index)

    for name, body in produced.items():
        path = target / name
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == body:
            continue
        if check:
            messages.append(
                f"{path.relative_to(index.root)} is out of date — "
                f"run `slpie context --skill`"
            )
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
        messages.append(f"wrote {path.relative_to(index.root)}")

    return messages
