"""`docs/INSTALL.md`, emitted from the topology model rather than written.

A hand-written install document is wrong within two releases. It says port 8080
when the manifest opens 8765; it lists a prerequisite that was dropped; it
documents a command with a flag that was renamed. Every one of those is a
support ticket, and every one of them is invisible to the tests.

This one is wrong only if the *model* is wrong — the prerequisites are the ones
the chosen emitter actually needs, the ports are the ones the manifest declares,
and the commands are the ones the CLI accepts. It is the argument §18 makes for
generating it and the argument §25 makes for auditing the reference registry,
applied to the one document a new operator reads first.

── It reports the gaps too ──────────────────────────────────────────────

The emitters already say what they could not express. Printing that in the
install manual is the difference between an operator learning that compose has
no autoscaler *now* and learning it from a queue that never drains.
"""

from __future__ import annotations

from typing import Iterable

from . import emitters
from ._render import DEFAULT_OUTPUT
from .manifest import Deployment, Platform

#: What each platform needs installed before anything is applied. Named per
#: emitter rather than as one list, because a compose operator does not need
#: `kubectl` and telling them they do is how a document loses its reader.
PREREQUISITES = {
    "compose": ("docker (with the compose plugin)",),
    "kubernetes": ("kubectl, pointed at the target cluster",),
    "helm": ("helm 3", "kubectl, pointed at the target cluster"),
    "systemd": ("a Linux host with systemd", "root, for the install script"),
    "terraform": ("terraform >= 1.5", "credentials for the declared cloud"),
    "pipelines": ("a CI system: GitHub Actions, GitLab CI or Azure Pipelines",),
}

#: How each emitter's output is applied. The commands an operator types.
APPLY = {
    "compose": ("docker compose up -d",),
    "kubernetes": ("kubectl apply -f .",),
    "helm": ("helm upgrade --install slpie . --namespace {environment} --create-namespace",),
    "systemd": ("sudo ./install.sh",),
    "terraform": ("terraform init", "terraform plan", "terraform apply"),
    "pipelines": ("git add . && git commit -m 'deploy' && git push",),
}


def install_manual(deployment: Deployment, *, emitter: str = "") -> str:
    """The install document for one declared deployment."""
    chosen = emitter or emitters.default_for(deployment)
    lines: list[str] = [
        f"# Installing SLPIE — {deployment.environment}",
        "",
        "<!-- Generated by `slpie deploy manual`. Do not edit: the next render",
        "     overwrites it. The ports, prerequisites and commands below come",
        "     from the deployment manifest, so this document is wrong only if",
        "     the model is. -->",
        "",
        f"Platform **{deployment.platform.value}** on **{deployment.cloud.value}**, "
        f"rendered by the `{chosen}` emitter.",
        "",
        "## Before you start",
        "",
    ]
    lines += [f"* {item}" for item in PREREQUISITES.get(chosen, ("nothing in particular",))]
    lines += ["", "## What gets deployed", "", "| Component | Size | CPU | Memory | Reachable at |",
              "|---|---|---|---|---|"]
    for component in deployment.components:
        size = (f"{component.minimum}–{component.maximum} (elastic)"
                if component.elastic else str(component.size))
        lines.append(
            f"| `{component.name}` | {size} | {component.cpu or '—'} | "
            f"{component.memory or '—'} | "
            f"{('`' + component.ingress + '`') if component.ingress else '—'} |"
        )

    ports = _ports(deployment)
    if ports:
        lines += ["", "### Ports", ""]
        lines += [f"* `{name}` listens on **{port}**" for name, port in ports]

    stores = deployment.persistence.stores
    if stores:
        lines += ["", "### What it stores, and where", "",
                  "| Store | Engine | Size |", "|---|---|---|"]
        for store in stores:
            lines.append(f"| `{store.name}` | {store.engine} | {store.size or '—'} |")

    lines += ["", "## Render it", "", "```bash",
              f"slpie deploy render --emitter {chosen} --out {DEFAULT_OUTPUT}", "```",
              "",
              "Nothing is applied. Read the files — that is what they are for.",
              "", "## Apply it", "", "```bash"]
    lines += [
        command.format(environment=deployment.environment)
        for command in APPLY.get(chosen, ("# no apply command for this emitter",))
    ]
    lines += ["```", ""]

    gaps = emitters.gaps(deployment, emitter=chosen)
    if gaps:
        lines += [
            "## What this render does not do",
            "",
            "Stated here rather than discovered later. Every line is the "
            "emitter reporting its own limit.",
            "",
        ]
        lines += [f"* {gap}" for gap in gaps]
        lines.append("")

    lines += _verification(deployment)
    return "\n".join(lines)


def _ports(deployment: Deployment) -> list[tuple[str, int]]:
    from .emitters._common import port_for

    return [
        (component.name, port_for(component))
        for component in deployment.components
        if port_for(component)
    ]


def _verification(deployment: Deployment) -> list[str]:
    """How to know it worked — and the check that makes this platform's claim.

    §18's acceptance is reconciliation applied to itself: point SLPIE at the
    deployment it just produced and require zero deltas. An operator can run
    exactly that, which is why it is the last section rather than a test nobody
    outside this repository sees.
    """
    return [
        "## Check it worked",
        "",
        "```bash",
        "slpie deploy status              # declared against running",
        "```",
        "",
        "Then the stronger check — the platform describing its own "
        "infrastructure:",
        "",
        "```bash",
        f"slpie declare && slpie reconcile --severity high",
        "```",
        "",
        "Zero `DECLARED_NOT_FOUND` and zero `CONTRADICTED` against the topology "
        "you just deployed. If the platform cannot correctly describe its own "
        "infrastructure, its description of yours is not worth having.",
        "",
    ]
